# Build Stage

FROM python:3.9-slim As builder

# Defining work directoy

WORKDIR /app

# Copy dependency file first for efficient caching
COPY requirement.txt .
RUN pip install --no-cache-dir -r requirement.txt --target=/app/deps

# Copy application source code
COPY . .

#Here one stage is completed

#stage 2 starts here

# Final Distroless Stage
FROM gcr.io/distroless/python3-debian11
WORKDIR /app

# Copy dependencies from the builder stage
COPY --from=builder /app/deps /app/deps
COPY --from=builder /app .

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH="/app/deps"

# Expose the application port
EXPOSE 8000

# Run the application
CMD ["run.py"]


